theme: jekyll-theme-minimal
title: The Microbiome of Brazilian Soils
description: Here we map the microbial community of soils in Brazil and relate this information with the quality of the soil
layout: default
show_sidebar: TRUE
logo: /images/Fotoram.io.jpg
