---
title: 

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Explore the soil samples containing the microbial diversity of the Brazilian soils.

#### Select the samples of interest and explore the results


#### Interactive plots
##### Use the map below to group and study soil microbiome features.
```{r, echo=FALSE, message = FALSE, warning = FALSE}
library(leaflet)
library(upsetjs)

soil_samples_df <- read.delim(file = "Samples/Sample_metadata.txt")

# feed shared object
data_ct <- crosstalk::SharedData$new(soil_samples_df[,c(1,5,6,7,11,12,13)])

crosstalk::bscols(
  widths = c(6,6,8), device = "xs",
  
  leaflet(data_ct, width = "100%", height = 300) %>%
    addTiles() %>%
    addMarkers(),
  
  d3scatter::d3scatter(data = data_ct, ~Org.Matter, ~Alpha_div, ~Biome,
                         width = "100%", height = 300),

  DT::datatable(data_ct,rownames = FALSE, filter = 'top',
                width = 600, height = 600)
  )

#load data
data <- read.delim(file = "Samples/mock_all_data.txt")
#get taxas and biome
data_taxa <- data[,c(2:21, 26)]

aggreg_data <- aggregate(data_taxa[,1], list(data_taxa$Biome), sum)
colnames(aggreg_data)[1] <- "Biome"
colnames(aggreg_data)[2] <- "taxa1"

for(i in 2:20){
  x = aggregate(data_taxa[,i], list(data_taxa$Biome), sum)
  column = paste0("taxa", i)
  colnames(x)[2] = column
  aggreg_data <- cbind(aggreg_data, x[column])
}

#making mock data, in real data, chage 2000 to 1 or any threshold that represents a significant amount of a taxa in a sample
biome <- aggreg_data[,1]
aggreg_data[!aggreg_data >= 2000] <- 1
aggreg_data[!aggreg_data < 2000] <- 0
rownames(aggreg_data)<- biome
aggreg_data <- aggreg_data[,-1]
aggreg_data <- t(aggreg_data)
aggreg_data <- as.data.frame(aggreg_data)

#finally, upset plotting
upsetjs() %>%
  fromDataFrame(aggreg_data) %>%
  generateIntersections(min = 2, max = NULL, empty = F, order.by = "cardinality",
                        limit = NULL) %>%
  interactiveChart()
```
