---
title:

output: html_document
---

# Macronutrients Prototype

```{r setup}

library(knitr)
library(tidyverse)
library(plotly)
library(crosstalk)
library(ggthemes)
library(DT)
library(leaflet)

knitr::opts_chunk$set(echo = FALSE)
```

### Explore the soil samples containing the microbial diversity of the Brazilian soils.

#### Select sample names, biome and soil parameters

##### Use the table below to group and study soil chemical features.

```{r plotly-crosstalk echo=FALSE, message = FALSE, warning = FALSE}
#load data
data <- read.delim("Samples/mock_macronutrients.txt")
#select parameters
shared_data <- data %>% 
  select(Sample_ID, C, N, P, K, Lat, Long, Biome) %>% 
  SharedData$new()

#plot stars here, using plotly
#p <- shared_data %>% 
#  plot_ly(x = ~Lat, y = ~Long, color = ~Biome,
#              hoverinfo = "text",
#              text = ~paste("Sample:", Sample_ID,
#                            "<br>Carbon:", C,
#                            "<br>Nitrogen:", N,
#                            "<br>Potassium:", K,
#                            "<br>Phosphorus:", P)) %>% 
#  group_by(Biome) %>% 
#  add_markers(size = 3) %>%
#  layout(xaxis = list(title = "Latitude"),
#         yaxis = list(title = "Longitude"),
#         legend = list(font = list(size = 16)))

# Combining several selectors

bscols(#widths = c(3,7),
       list(
         #select region
            filter_checkbox(id = "Biome", label = "Biome",
                    sharedData = shared_data, group = ~Biome),
            #select sample
            filter_select(id = "Sample_ID", label = "Sample_ID",
                    sharedData = shared_data, group = ~Sample_ID),
            #add carbon slider
            filter_slider(id = "carbon", label = "Carbon",
                    sharedData = shared_data, column = ~C),
            #add nitrogen slider
            filter_slider(id = "nitrogen", label = "Nitrogen",
                    sharedData = shared_data, column = ~N),
            #add phosphorous slider
            filter_slider(id = "phosphorus", label = "Phosphorus",
                    sharedData = shared_data, column = ~P),
            #add potassium slider
            filter_slider(id = "potassium", label = "Potassium",
                    sharedData = shared_data, column = ~K)
      ),
       leaflet(shared_data, width = "100%", height = 500) %>%
        addTiles() %>%
        addMarkers(),
      d3scatter::d3scatter(data = shared_data, ~C, ~N, ~Biome,
                         width = "100%", height = 300)#,
      #p #when using plotly
    )
DT::datatable(shared_data,
              rownames = FALSE, 
              options = list(dom = 't',
                             buttons = c('copy', 'csv', 'excel', 'pdf', 'print')),
              width = "100%", height = "100%")

```
