---
title:

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taxa Map</title>
</head>
<body>
    <header>
        <h2>Taxa map</h2>
    </header>
    <h3>Search taxa across the samples</h3>
</body>
</html>
```
### Explore the soil samples containing the microbial diversity of the Brazilian soils.

#### Select the samples or taxa of interest and explore the results

##### Use the table below to group and study soil microbiome features.

```{r, echo=FALSE, message = FALSE, warning = FALSE}
library(leaflet)
mock_samples_df <- read.delim(file = "Samples/reduced_taxa_mock.txt")

# feed shared object

DT::datatable(mock_samples_df,
              rownames = FALSE,
              filter = 'top',
              options = list(pageLength = 5, 
                             autoWidth = TRUE, 
                             dom = 'Blfrtip',
                             buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                             lengthMenu = list(c(10,25,50,-1),
                                            c(10,25,50,"All"))),
              height = 600,
              extensions = "Buttons")
```
```{=html}
<div class="list_container">
  <ul class="menu">
    <li><a href="{{ site.github.tar_url }}">Download <strong>TAR Ball</strong></a></li>
    <li><a href="{{ site.github.zip_url }}">Download <strong>ZIP File</strong></a></li>
    <li><a href="{{ site.github.repository_url }}">View On <strong>GitHub</strong></a></li>
    <li><a href="taxa.html" target="_blank" rel="noopener noreferrer">Get map by <strong>Taxa</strong></a></li>
    <li><a href="under_construction.html" target="_blank" rel="noopener noreferrer">Precipitation <strong>Gradients</strong></a></li>
    <li><a href="under_construction.html" target="_blank" rel="noopener noreferrer">Macronutrient <strong>Effects</strong></a></li>
  </ul>
</div>
```
