---
title: Template
output: html_document

params:
  taxa: "taxa1"
  name: "Name namus"
---

# Organism: `r params$name`

```{r setup, include=FALSE}
params
library(knitr)
library(tidyverse)
library(upsetjs)
library(qtlcharts)
library(DT)

data <- read.delim(file = "Samples/mock_all_data.txt")
x <- ncol(data)-6
y <- ncol(data)      
data_soil <- data[,x:y]
rm(x,y)
data_taxa <- data[,params$taxa]
data_single <- cbind(data_taxa, data_soil)
colnames(data_single[1]) <- params$name
rownames(data_single) <- data$Sample_ID

knitr::opts_chunk$set(echo = FALSE)
```

##The sumary data table for `r params$name`.

```{r, echo=FALSE, message = FALSE, warning = FALSE}

datatable(data_single,
                rownames = FALSE,
                filter = 'top',
                options = list(pageLength = 5, 
                               autoWidth = TRUE, 
                               dom = 'Blfrtip',
                               buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                               lengthMenu = list(c(10,25,50,-1),
                                              c(10,25,50,"All"))),
                height = 600,
                extensions = "Buttons")
```